OBJECTS = src/life.c
INCLUDE_PATHS = ""
LIBRARY_PATHS = ""
LINKER_FLAGS = ""
COMPILER_FLAGS = -Wall
OUTPUT = ./build/life

all:
	cc $(OBJECTS) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OUTPUT)
